### ISSUE TITLE
Inject Sass framework (бурбон?)

### ISSUE THREAD

**Issue by dhilt** [voops/orden-muzeev-frontend#9]

**Comment by voops** [comment]
Пробовал решить задачу через редактирование `config/webpack.common.js`:
```
...
{
    test: /\.scss$/,
    include: [
        path.resolve(__dirname, "src"),
        path.resolve(__dirname, "node_modules/bourbon")
    ],
    loaders: ['style', 'css', 'sass']
}
```
Но во время сборки начали сыпаться ошибки - лоадеры перестали понимать синтаксис sass. Похоже, здесь описана такая же проблема: https://github.com/jtangelder/sass-loader/issues/69 .

**Comment by voops** [comment]
https://github.com/voops/orden-muzeev-frontend/tree/feature/add-bourbon-mixins
